POST https://crud-fastify.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://crud-fastify.onrender.com/videos

###

PUT https://crud-fastify.onrender.com/videos/
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE https://crud-fastify.onrender.com/videos/